# -*- coding: utf-8 -*-
"""yolov5_trainning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U0aXpEDjOql5H8m5oXGSMiJ6znMEqcTf

# **사전 설치**
"""

from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5
# %pip install -qr requirements.txt

"""# **Train set, Valid set, Test set 나누기**"""

!pip install split-folders tqdm

import splitfolders
splitfolders.ratio('/content/drive/MyDrive/Colab_Notebooks/fire_indoor_images/fire',  # 자기 폴더로 바꿔야됨. (fire 라는 폴더 아래 하위 폴더가 존재해야됨(class)로 할,)
                   output="/content/drive/MyDrive/Colab_Notebooks/images", 
                   seed=77, ratio=(.8, 0.1, 0.1))

"""# **튜토리얼 학습**"""

!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt

"""# **그림을 위한 설치**"""

!pip install wandb

"""결과는 yolov5/runs/train/exp/results.csv에 결과 저장
이미지는 yolov5/runs/train/exp/results.png에 결과 저장
"""

from utils.plots import plot_results
plot_results('runs/train/exp/results.png')  # plot 'results.csv' as 'results.png'

"""# **학습 결과를 다운로드하고 싶다면, 내용 모두 압축하여 저장**"""

!zip -r train_result.zip runs/train/exp

"""# **검증하기는 생략, 바로 적용해보기**
테스트 결과는 ```/runs/detect/exp``` 경로에 저장
"""

!python detect.py --source 'https://www.youtube.com/watch?v=mI9oyFMUlfg'  # YouTube

!zip -r test_result.zip runs/detect/exp